// web3
export const SET_WEB3_BUFFERING = 'SET_WEB3_BUFFERING';
export const SET_WALLET_ADDRESS = 'SET_WALLET_ADDRESS';
export const SET_CURRENT_CHAIN = 'SET_CURRENT_CHAIN';
export const INIT_WALLET_ADDRESS = 'INIT_WALLET_ADDRESS';
export const INIT_CURRENT_CHAIN = 'INIT_CURRENT_CHAIN';

